### ISSUE TITLE
after Strava subscription changes only offers 60 days for any link

### ISSUE THREAD

**Issue by thisisgregm** [53RT/Strava-Promo-Codes#3]
As you probably know Strava did some changes to their subscription offer and remove some features from a free subscription.
All of the links have all the right message (for example 90 days), but on the bottom of any of them says the same: "Start free 60 day trial".
Perhaps we have to wait for a new 90-days promo links generated after the Strava changes mid May.

**Comment by 53RT** [comment]
Hi,
thank you for your comment. Haven't checked the links after the changes but you are right. I noticed that you are still forwarded to different URLs and the button to start the 60 day trial has different payload parameter so there might be a chance for us.

See the following links for example:
https://www.strava.com/summit/checkout?package_ids=4,5,6&trial_code=england-athletics
https://www.strava.com/summit/checkout?package_ids=4,5,6&trial_code=2016BritishCyclingTrial

**Comment by thisisgregm** [comment]
Those links still give me 60 days trial, not 90. Looking forward to get some new promo links with 90. Thanks for your work on that!

**Comment by mteper** [comment]
Frankly, given the recent announcements out of Strava, I’m not holding my breath. I like the app and find it valuable, so I’ll take the 60 days and start paying in a couple of months.

**Comment by mteper** [comment]
Good news, the 90-day code link seems to work and offer 90 day trial today.

**Comment by thisisgregm** [comment]
60 days for me :(

**Comment by bessone** [comment]
For me all links don't work. They always refer to the normal registration page (I used a promo in the past, then I was premium for two years, I don't know if it can count)

**Comment by millanium** [comment]
Same here. Any promo link leads to the payout now.

**Comment by 53RT** [comment]
As you have all noticed, Strava has changed the trial membership mechanism, and it seems that users cannot have a new trial membership if they already had one.
The trial days may also differ from the specified duration. Since the links are still valid for users without a trial period, I would leave them here, and maybe they will lead to more Strava premium subscriptions.
