### ISSUE TITLE
Add privacy.com generated card to avoid billing ?

### ISSUE THREAD

**Issue by CruiseMan** [53RT/Strava-Promo-Codes#4]
So glad to find this repo. How do you guys think, should we add privacy.com instruction to generate virtual card that can be used for trial sign up instead using personal card ?.

**Comment by 53RT** [comment]
Hi CruiseMan,
thank you for your contribution. I intended this repo to be a link list without recommendations. I have no experience with privacy.com and do not see the need to use this service with strava. And there is also the option to use paypal for the billing.
